/*
 * Created on 2019-05-09 ( Date ISO 2019-05-09 - Time 11:12:20 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package com.cpa.ehr.backend.dao.patients.entities;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.*;

@Entity
@Table(name="lab_results", schema="ehr" )
public class LabResults implements Serializable {

	private static final long serialVersionUID = 1L;

	//----------------------------------------------------------------------
	// ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
	//----------------------------------------------------------------------
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "sequenceGenerator")
	@SequenceGenerator(name = "sequenceGenerator", sequenceName = "lab_id_seq", initialValue=1, allocationSize = 1)
	@Column(name = "lab_id")
	private Long labId ;  

	//----------------------------------------------------------------------
	// ENTITY DATA FIELDS 
	//----------------------------------------------------------------------    


	@Column(name="patient_id")
	private Long patientId ;

	@Column(name="results_comments", length=500)
	private String resultsComments ;

	@Column(name="document_link", length=500)
	private String documentLink ;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="lab_date")
	private Date labDate ;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="created_date")
	private Date createdDate ;

	@Column(name="created_by", length=500)
	private String createdBy ;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="last_updated_date")
	private Date lastUpdatedDate ;

	@Column(name="last_updated_by", length=500)
	private String lastUpdatedBy ;

	@Column(name="active_flag", length=1)
	private String activeFlag ;



	//----------------------------------------------------------------------
	// CONSTRUCTOR(S)
	//----------------------------------------------------------------------
	public LabResults() {
		super();
	}

	//----------------------------------------------------------------------
	// GETTER & SETTER FOR THE KEY FIELD
	//----------------------------------------------------------------------
	public void setLabId(Long labId) {
		this.labId = labId ;
	}
	public Long getLabId() {
		return this.labId;
	}

	//----------------------------------------------------------------------
	// GETTERS & SETTERS FOR FIELDS
	//----------------------------------------------------------------------
	//--- DATABASE MAPPING : patient_id (int8) 
	public void setPatientId(Long patientId)
	{this.patientId = patientId;}


	public Long getPatientId()
	{return this.patientId;}


	//--- DATABASE MAPPING : results_comments (varchar) 
	public void setResultsComments(String resultsComments)
	{this.resultsComments = resultsComments;}


	public String getResultsComments()
	{return this.resultsComments;}


	//--- DATABASE MAPPING : document_link (varchar) 
	public void setDocumentLink(String documentLink)
	{this.documentLink = documentLink;}


	public String getDocumentLink()
	{return this.documentLink;}


	//--- DATABASE MAPPING : lab_date (timestamptz) 
	public void setLabDate(Date labDate)
	{this.labDate = labDate;}


	public Date getLabDate()
	{return this.labDate;}


	//--- DATABASE MAPPING : created_date (timestamptz) 
	public void setCreatedDate(Date createdDate)
	{this.createdDate = createdDate;}


	public Date getCreatedDate()
	{return this.createdDate;}


	//--- DATABASE MAPPING : created_by (varchar) 
	public void setCreatedBy(String createdBy)
	{this.createdBy = createdBy;}


	public String getCreatedBy()
	{return this.createdBy;}


	//--- DATABASE MAPPING : last_updated_date (timestamptz) 
	public void setLastUpdatedDate(Date lastUpdatedDate)
	{this.lastUpdatedDate = lastUpdatedDate;}


	public Date getLastUpdatedDate()
	{return this.lastUpdatedDate;}


	//--- DATABASE MAPPING : last_updated_by (varchar) 
	public void setLastUpdatedBy(String lastUpdatedBy)
	{this.lastUpdatedBy = lastUpdatedBy;}


	public String getLastUpdatedBy()
	{return this.lastUpdatedBy;}


	//--- DATABASE MAPPING : active_flag (varchar) 
	public void setActiveFlag(String activeFlag)
	{this.activeFlag = activeFlag;}


	public String getActiveFlag()
	{return this.activeFlag;}




	//----------------------------------------------------------------------
	// toString METHOD
	//----------------------------------------------------------------------
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
		sb.append("LabResults");
		sb.append("labId :");
		sb.append(labId); 
		sb.append("patientId :");
		sb.append(patientId); 
		sb.append("|"); 
		sb.append("resultsComments :");
		sb.append(resultsComments); 
		sb.append("|"); 
		sb.append("documentLink :");
		sb.append(documentLink); 
		sb.append("|"); 
		sb.append("labDate :");
		sb.append(labDate); 
		sb.append("|"); 
		sb.append("createdDate :");
		sb.append(createdDate); 
		sb.append("|"); 
		sb.append("createdBy :");
		sb.append(createdBy); 
		sb.append("|"); 
		sb.append("lastUpdatedDate :");
		sb.append(lastUpdatedDate); 
		sb.append("|"); 
		sb.append("lastUpdatedBy :");
		sb.append(lastUpdatedBy); 
		sb.append("|"); 
		sb.append("activeFlag :");
		sb.append(activeFlag); 
		return sb.toString();
	}
}