export class PatientRecord {
  constructor(
    public patientId: number, 
    public activeFlag: string,
    public additionalInfo: string ,
    public dob: Date, 
    public emrId: string,
    public firstName: string , 
    public middleName: string ,
    public lastName: string,
    public gender: string,
    public patientApartmentNo:string,
    public patientCity:string,
    public patientImage:Blob,
    public patientState:string,
    public patientStreetAddress:string,
    public primaryEmail: string ,
    public secondaryEmail: string ,
    public primaryNo: string,
    public secondaryNo: string,
    public zipCode:string,
    public primaryLocation:number,
    public organizationId:number,
    public primaryProvider:number,
    public providerFirstName:string,
    public providerMiddleName:string,
    public providerLastName:string,
    public providerFlag:string,
    public providerType:string,
    public designation:string,
    public mobileNo :string,
    public businessPhoneNo:string,
    public email:string,
    public npiNumber:string,
    public clinicCity:string,
    public clinicAddressDoorNo:string,
    public clinicAddressState:string,
    public clinicAddressStreet:string,
    public clinicAddressZip:string,
    public clinicContactEmail:string,
    public clinicContactName:string,
    public einNumber:string,
    public clinicFaxNo:string,
    public clinicLocName:string,
    public clinicPrimaryNo:string,
    public createdDate: Date,
		public createdBy: string,
		public lastUpdatedDate: Date,
		public lastUpdatedBy: string,
    public mrn: string
  )
  {}
  }