/*
 * Created on 2019-04-25 ( Date ISO 2019-04-25 - Time 10:19:38 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.ehr.backend.dao.system;

import java.util.List;

//
//import org.demo.entity.PatientAllergy;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import com.cpa.ehr.backend.dao.system.constants.PatientAllergyConstant;
import com.cpa.ehr.backend.dao.system.entities.PatientAllergy;

/**
 * Jpa repository for PatientAllergy.

 */
@Repository
public interface PatientAllergyRepository  extends JpaRepository<PatientAllergy, Long> {
	
	@Query(value = PatientAllergyConstant.FIND_ALL, nativeQuery = true)
	List<PatientAllergy> getAllPatientAllergyByPatientId(@Param("patientId") Long patientId);
}