/*
 * Created on 2021-05-06 ( Date ISO 2021-05-06 - Time 17:00:23 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.idms.service.admin;

import com.cpa.idms.backend.dao.admin.entities.DocumentsVersionWorkflowComments;
import com.cpa.idms.backend.dao.exception.entities.IdmsBaseException;
import com.cpa.idms.service.admin.dto.DocumentsVersionWorkflowCommentsDTO;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import java.util.List;


public interface DocumentsVersionWorkflowCommentsService {


	DocumentsVersionWorkflowCommentsDTO insertDocumentsVersionWorkflowComments(DocumentsVersionWorkflowCommentsDTO documentsVersionWorkflowCommentsDTOinsert) throws IdmsBaseException;
  	DocumentsVersionWorkflowCommentsDTO retrieveDocumentsVersionWorkflowCommentsById(Long documentsVersionWorkflowCommentsId) throws IdmsBaseException;
	List<DocumentsVersionWorkflowCommentsDTO> retrieveAllDocumentsVersionWorkflowComments() throws IdmsBaseException;
	DocumentsVersionWorkflowCommentsDTO updateDocumentsVersionWorkflowComments(DocumentsVersionWorkflowCommentsDTO documentsVersionWorkflowCommentsDTOUpdate) throws IdmsBaseException;
	  	Boolean deleteById(Long documentsVersionWorkflowCommentsId) throws IdmsBaseException;
	}
