/*
 * Created on 2021-05-06 ( Date ISO 2021-05-06 - Time 17:00:24 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.idms.service.admin;

import com.cpa.idms.backend.dao.exception.entities.IdmsBaseException;
import com.cpa.idms.service.admin.dto.ProjectDocumentsDTO;

import java.util.List;


public interface ProjectDocumentsService {


	ProjectDocumentsDTO insertProjectDocuments(ProjectDocumentsDTO projectDocumentsDTOinsert) throws IdmsBaseException;
  	ProjectDocumentsDTO retrieveProjectDocumentsById(Long projectDocumentsId) throws IdmsBaseException;
	List<ProjectDocumentsDTO> retrieveAllProjectDocuments() throws IdmsBaseException;
	ProjectDocumentsDTO updateProjectDocuments(ProjectDocumentsDTO projectDocumentsDTOUpdate) throws IdmsBaseException;
	Boolean deleteById(Long projectDocumentsId) throws IdmsBaseException;
	}
