/*
 * Created on 2021-05-06 ( Date ISO 2021-05-06 - Time 17:00:24 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.idms.service.admin;

import com.cpa.idms.backend.dao.exception.entities.IdmsBaseException;
import com.cpa.idms.service.admin.dto.ProjectDocumentsVersionDTO;

import java.util.List;


public interface ProjectDocumentsVersionService {


	ProjectDocumentsVersionDTO insertProjectDocumentsVersion(ProjectDocumentsVersionDTO projectDocumentsVersionDTOinsert) throws IdmsBaseException;
  	ProjectDocumentsVersionDTO retrieveProjectDocumentsVersionById(Long projectDocumentsVersionId) throws IdmsBaseException;
	List<ProjectDocumentsVersionDTO> retrieveAllProjectDocumentsVersion() throws IdmsBaseException;
	ProjectDocumentsVersionDTO updateProjectDocumentsVersion(ProjectDocumentsVersionDTO projectDocumentsVersionDTOUpdate) throws IdmsBaseException;
	Boolean deleteById(Long projectDocumentsVersionId) throws IdmsBaseException;
	}
