/*
 * Created on 2021-05-06 ( Date ISO 2021-05-06 - Time 17:00:24 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.idms.service.admin;

import com.cpa.idms.backend.dao.exception.entities.IdmsBaseException;
import com.cpa.idms.service.admin.dto.ProjectUserDTO;

import java.util.List;


public interface ProjectUserService {


	ProjectUserDTO insertProjectUser(ProjectUserDTO projectUserDTOinsert) throws IdmsBaseException;
  	ProjectUserDTO retrieveProjectUserById(Long projectUserId) throws IdmsBaseException;
	List<ProjectUserDTO> retrieveAllProjectUser() throws IdmsBaseException;
	ProjectUserDTO updateProjectUser(ProjectUserDTO projectUserDTOUpdate) throws IdmsBaseException;
	Boolean deleteById(Long projectUserId) throws IdmsBaseException;
	}
