/*
 * Created on 2021-05-06 ( Date ISO 2021-05-06 - Time 17:00:25 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.idms.service.admin;

import com.cpa.idms.backend.dao.exception.entities.IdmsBaseException;
import com.cpa.idms.service.admin.dto.WorkflowTemplateDTO;

import java.util.List;


public interface WorkflowTemplateService {


	WorkflowTemplateDTO insertWorkflowTemplate(WorkflowTemplateDTO workflowTemplateDTOinsert) throws IdmsBaseException;
  	WorkflowTemplateDTO retrieveWorkflowTemplateById(Long workflowTemplateId) throws IdmsBaseException;
	List<WorkflowTemplateDTO> retrieveAllWorkflowTemplate() throws IdmsBaseException;
	WorkflowTemplateDTO updateWorkflowTemplate(WorkflowTemplateDTO workflowTemplateDTOUpdate) throws IdmsBaseException;
	  	Boolean deleteById(Long workflowTemplateId) throws IdmsBaseException;
	}
