/*
 * Created on 2021-05-06 ( Date ISO 2021-05-06 - Time 17:00:25 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.idms.service.admin;

import com.cpa.idms.backend.dao.exception.entities.IdmsBaseException;
import com.cpa.idms.service.admin.dto.WorkflowTemplateDetailsDTO;

import java.util.List;


public interface WorkflowTemplateDetailsService {


	WorkflowTemplateDetailsDTO insertWorkflowTemplateDetails(WorkflowTemplateDetailsDTO workflowTemplateDetailsDTOinsert) throws IdmsBaseException;
  	WorkflowTemplateDetailsDTO retrieveWorkflowTemplateDetailsById(Long workflowTemplateDetailsId) throws IdmsBaseException;
	List<WorkflowTemplateDetailsDTO> retrieveAllWorkflowTemplateDetails() throws IdmsBaseException;
	WorkflowTemplateDetailsDTO updateWorkflowTemplateDetails(WorkflowTemplateDetailsDTO workflowTemplateDetailsDTOUpdate) throws IdmsBaseException;
	Boolean deleteById(Long workflowTemplateDetailsId) throws IdmsBaseException;
	}
