/*
 * Created on 2021-05-06 ( Date ISO 2021-05-06 - Time 17:00:23 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.idms.service.admin.dto.mapper;

import java.util.List;

import com.cpa.idms.backend.dao.admin.entities.DocumentsVersionWorkflowComments;
import com.cpa.idms.service.admin.dto.DocumentsVersionWorkflowCommentsDTO;

import org.mapstruct.Mapper;
/**
 * DocumentsVersionWorkflowCommentsDTO's Mapper declaration using selma.
 * @author Rajol version 3.0.0
 */
@Mapper(componentModel = "spring")
public abstract class DocumentsVersionWorkflowCommentsMapper {

	// This will build a fresh new DocumentsVersionWorkflowCommentsDTO with in infos
		
public abstract  DocumentsVersionWorkflowCommentsDTO convertEntityToDocumentsVersionWorkflowCommentsDTO(DocumentsVersionWorkflowComments entity);
	
public abstract  DocumentsVersionWorkflowComments  convertDocumentsVersionWorkflowCommentsDTOToEntity( DocumentsVersionWorkflowCommentsDTO dto);

public abstract List<DocumentsVersionWorkflowCommentsDTO>  entityListToDocumentsVersionWorkflowCommentsDTOList(List<DocumentsVersionWorkflowComments> entities);
}
