/*
 * Created on 2021-05-06 ( Date ISO 2021-05-06 - Time 17:00:23 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.idms.service.admin.dto.mapper;

import java.util.List;

import com.cpa.idms.backend.dao.admin.entities.DocumentsVersionWorkflow;
import com.cpa.idms.service.admin.dto.DocumentsVersionWorkflowDTO;

import org.mapstruct.Mapper;
/**
 * DocumentsVersionWorkflowDTO's Mapper declaration using selma.
 * @author Rajol version 3.0.0
 */
@Mapper(componentModel = "spring")
public abstract class DocumentsVersionWorkflowMapper {

	// This will build a fresh new DocumentsVersionWorkflowDTO with in infos
		
public abstract  DocumentsVersionWorkflowDTO convertEntityToDocumentsVersionWorkflowDTO(DocumentsVersionWorkflow entity);
	
public abstract  DocumentsVersionWorkflow  convertDocumentsVersionWorkflowDTOToEntity( DocumentsVersionWorkflowDTO dto);

public abstract List<DocumentsVersionWorkflowDTO>  entityListToDocumentsVersionWorkflowDTOList(List<DocumentsVersionWorkflow> entities);
}
