/*
 * Created on 2021-05-06 ( Date ISO 2021-05-06 - Time 17:00:24 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.idms.service.admin.dto.mapper;

import java.util.List;

import com.cpa.idms.backend.dao.admin.entities.ProjectDocuments;
import com.cpa.idms.service.admin.dto.ProjectDocumentsDTO;

import org.mapstruct.Mapper;
/**
 * ProjectDocumentsDTO's Mapper declaration using selma.
 * @author Rajol version 3.0.0
 */
@Mapper(componentModel = "spring")
public abstract class ProjectDocumentsMapper {

	// This will build a fresh new ProjectDocumentsDTO with in infos
		
public abstract  ProjectDocumentsDTO convertEntityToProjectDocumentsDTO(ProjectDocuments entity);
	
public abstract  ProjectDocuments  convertProjectDocumentsDTOToEntity( ProjectDocumentsDTO dto);

public abstract List<ProjectDocumentsDTO>  entityListToProjectDocumentsDTOList(List<ProjectDocuments> entities);
}
