/*
 * Created on 2021-05-06 ( Date ISO 2021-05-06 - Time 17:00:24 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.idms.service.admin.dto.mapper;

import java.util.List;

import com.cpa.idms.backend.dao.admin.entities.ProjectDocumentsVersion;
import com.cpa.idms.service.admin.dto.ProjectDocumentsVersionDTO;

import org.mapstruct.Mapper;
/**
 * ProjectDocumentsVersionDTO's Mapper declaration using selma.
 * @author Rajol version 3.0.0
 */
@Mapper(componentModel = "spring")
public abstract class ProjectDocumentsVersionMapper {

	// This will build a fresh new ProjectDocumentsVersionDTO with in infos
		
public abstract  ProjectDocumentsVersionDTO convertEntityToProjectDocumentsVersionDTO(ProjectDocumentsVersion entity);
	
public abstract  ProjectDocumentsVersion  convertProjectDocumentsVersionDTOToEntity( ProjectDocumentsVersionDTO dto);

public abstract List<ProjectDocumentsVersionDTO>  entityListToProjectDocumentsVersionDTOList(List<ProjectDocumentsVersion> entities);
}
