/*
 * Created on 2021-05-06 ( Date ISO 2021-05-06 - Time 17:00:26 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.idms.service.admin.dto.mapper;

import java.util.List;

import com.cpa.idms.backend.dao.admin.entities.WorkflowTemplateDetails;
import com.cpa.idms.service.admin.dto.WorkflowTemplateDetailsDTO;

import org.mapstruct.Mapper;
/**
 * WorkflowTemplateDetailsDTO's Mapper declaration using selma.
 * @author Rajol version 3.0.0
 */
@Mapper(componentModel = "spring")
public abstract class WorkflowTemplateDetailsMapper {

	// This will build a fresh new WorkflowTemplateDetailsDTO with in infos
		
public abstract  WorkflowTemplateDetailsDTO convertEntityToWorkflowTemplateDetailsDTO(WorkflowTemplateDetails entity);
	
public abstract  WorkflowTemplateDetails  convertWorkflowTemplateDetailsDTOToEntity( WorkflowTemplateDetailsDTO dto);

public abstract List<WorkflowTemplateDetailsDTO>  entityListToWorkflowTemplateDetailsDTOList(List<WorkflowTemplateDetails> entities);
}
