/*
 * Created on 2021-05-06 ( Date ISO 2021-05-06 - Time 17:00:25 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.idms.service.admin.dto.mapper;

import java.util.List;

import com.cpa.idms.backend.dao.admin.entities.WorkflowTemplate;
import com.cpa.idms.service.admin.dto.WorkflowTemplateDTO;

import org.mapstruct.Mapper;
/**
 * WorkflowTemplateDTO's Mapper declaration using selma.
 * @author Rajol version 3.0.0
 */
@Mapper(componentModel = "spring")
public abstract class WorkflowTemplateMapper {

	// This will build a fresh new WorkflowTemplateDTO with in infos
		
public abstract  WorkflowTemplateDTO convertEntityToWorkflowTemplateDTO(WorkflowTemplate entity);
	
public abstract  WorkflowTemplate  convertWorkflowTemplateDTOToEntity( WorkflowTemplateDTO dto);

public abstract List<WorkflowTemplateDTO>  entityListToWorkflowTemplateDTOList(List<WorkflowTemplate> entities);
}
