/*
 * Created on 2019-04-25 ( Date ISO 2019-04-25 - Time 10:19:38 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.ehr.service.system;

import java.util.List;

import org.springframework.stereotype.Service;

import com.cpa.ehr.service.system.dto.PatientAllergyDTO;
import com.cpa.ehr.service.system.dto.PatientMedicationDTO;

@Service(value="patientallergyService")
public interface PatientAllergyService {


	PatientAllergyDTO persistPatientAllergy(PatientAllergyDTO patientAllergyDTOpersist) ;


 // PatientAllergyDTO retrieveById(Long patientAllergyId);


	List<PatientAllergyDTO>retrieveByPatientId(Long patientId);
	
	void deletePatientAllergy(Long patientAllergyId);

	//PatientAllergyDTO updatePatientAllergy(PatientAllergyDTO patientAllergyDTOUpdate) ;
	//public void deleteById(Long patientAllergyId);
	
	}
