/*
 * Created on 2021-05-06 ( Date ISO 2021-05-06 - Time 17:00:23 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.idms.web.rest.admin;


import javax.validation.Valid;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.CrossOrigin;
import java.util.List;
import org.springframework.web.bind.annotation.RequestParam;
import com.cpa.idms.backend.dao.admin.entities.StaffMember;
import com.cpa.idms.backend.dao.exception.entities.IdmsBaseException;
import com.cpa.idms.service.admin.DocumentsVersionWorkflowService;
import com.cpa.idms.service.admin.IDMSBaseService;
import com.cpa.idms.service.admin.dto.DocumentsVersionWorkflowDTO;
import com.cpa.idms.util.FormatConverterUtils;



/**
 * Rest controller which produce Hal+json content (including hateoas metadata).
 * @author Rajol version 3.0.0
 */
@RestController
@RequestMapping("/api/rest")
@CrossOrigin(origins = { "http://localhost:4300" })
public class DocumentsVersionWorkflowWebService {

	private static final Logger LOG = LoggerFactory.getLogger( DocumentsVersionWorkflowWebService.class);


	@Autowired
	private  DocumentsVersionWorkflowService documentsVersionWorkflowService;

	@Autowired
	private IDMSBaseService idmsBaseService;

	
	@PostMapping("/createDocumentsVersionWorkflow")
	public ResponseEntity<DocumentsVersionWorkflowDTO> insertDocumentsVersionWorkflow(@RequestBody DocumentsVersionWorkflowDTO documentsVersionWorkflowDTO){
		try{
				if(documentsVersionWorkflowDTO!=null) {				
					StaffMember loginUser = idmsBaseService.currentUser();
					FormatConverterUtils.setInitialDefaultValues(documentsVersionWorkflowDTO, loginUser);
				
					DocumentsVersionWorkflowDTO datadocumentsVersionWorkflowDTO = documentsVersionWorkflowService.insertDocumentsVersionWorkflow(documentsVersionWorkflowDTO);
					return new ResponseEntity<> (datadocumentsVersionWorkflowDTO, HttpStatus.OK);
			}
		}catch (Exception e) {
			LOG.error("Error while inserting DocumentsVersionWorkflow {}",e);
		}
		
		HttpHeaders headers= new HttpHeaders();
		return new ResponseEntity<>(headers, HttpStatus.NOT_IMPLEMENTED);
	}

	@GetMapping("/getAllDocumentsVersionWorkflow")
	public ResponseEntity<List<DocumentsVersionWorkflowDTO>> getAllDocumentsVersionWorkflow() {
		List<DocumentsVersionWorkflowDTO> documentsVersionWorkflowDTOResp;
		try {
			documentsVersionWorkflowDTOResp = documentsVersionWorkflowService.retrieveAllDocumentsVersionWorkflow();
			return new ResponseEntity<> (documentsVersionWorkflowDTOResp, HttpStatus.OK);

		} catch (IdmsBaseException e) {
			LOG.error("Error while retrieving all  DocumentsVersionWorkflow {}",e);
		}
		HttpHeaders headers= new HttpHeaders();
		return new ResponseEntity<>(headers, HttpStatus.NOT_IMPLEMENTED);
	}

		@GetMapping("/getDocumentsVersionWorkflowById")
	public ResponseEntity<DocumentsVersionWorkflowDTO> getDocumentsVersionWorkflowById(@RequestParam("id") Long documentsVersionWorkflowId) {
	DocumentsVersionWorkflowDTO documentsVersionWorkflowDTO;
		try {
			documentsVersionWorkflowDTO =  documentsVersionWorkflowService.retrieveDocumentsVersionWorkflowById( documentsVersionWorkflowId);
			return new ResponseEntity<> (documentsVersionWorkflowDTO, HttpStatus.OK);
		} catch (IdmsBaseException e) {
			LOG.error("Error while retrieving By DocumentsVersionWorkflow ID {}",e);
		}
		HttpHeaders headers= new HttpHeaders();
		return new ResponseEntity<>(headers , HttpStatus.NOT_IMPLEMENTED);
	}


	
	@PutMapping("/updateDocumentsVersionWorkflow")
	public ResponseEntity<DocumentsVersionWorkflowDTO> updateDocumentsVersionWorkflow(@RequestBody DocumentsVersionWorkflowDTO documentsVersionWorkflowDTO){
		try{
			  if(documentsVersionWorkflowDTO!=null) {				
				StaffMember loginUser = idmsBaseService.currentUser();
				FormatConverterUtils.setInitialDefaultValues(documentsVersionWorkflowDTO, loginUser);
				DocumentsVersionWorkflowDTO datadocumentsVersionWorkflowDTO = documentsVersionWorkflowService.updateDocumentsVersionWorkflow(documentsVersionWorkflowDTO);
				return new ResponseEntity<> (datadocumentsVersionWorkflowDTO, HttpStatus.OK);
			}
		}catch (Exception e) {
			LOG.error("Error while updating DocumentsVersionWorkflow {}",e);
		}
		
		HttpHeaders headers= new HttpHeaders();
		return new ResponseEntity<>(headers, HttpStatus.NOT_IMPLEMENTED);
	}


	@DeleteMapping("/removeDocumentsVersionWorkflowById")
	public ResponseEntity<Void> deleteDocumentsVersionWorkflowById(@Valid @RequestParam("id") Long documentsVersionWorkflowId){
	HttpHeaders headers= new HttpHeaders();
		try {
			Boolean flag = documentsVersionWorkflowService.deleteById(documentsVersionWorkflowId);
			if(flag)
				return new ResponseEntity<> (headers, HttpStatus.OK);
			else
				return new ResponseEntity<>(headers, HttpStatus.NOT_IMPLEMENTED);
		}catch (Exception e) {
			LOG.error("Error while deleting By DocumentsVersionWorkflow ID {}",e);
		}
		
		return new ResponseEntity<>(headers, HttpStatus.NOT_IMPLEMENTED);
	
	}

}










