/*
 * Created on 2021-05-06 ( Date ISO 2021-05-06 - Time 17:00:23 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.idms.web.rest.admin;


import javax.validation.Valid;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.CrossOrigin;
import java.util.List;
import org.springframework.web.bind.annotation.RequestParam;
import com.cpa.idms.backend.dao.admin.entities.StaffMember;
import com.cpa.idms.backend.dao.exception.entities.IdmsBaseException;
import com.cpa.idms.service.admin.IDMSBaseService;
import com.cpa.idms.service.admin.MasterLookupService;
import com.cpa.idms.service.admin.dto.MasterLookupDTO;
import com.cpa.idms.util.FormatConverterUtils;



/**
 * Rest controller which produce Hal+json content (including hateoas metadata).
 * @author Rajol version 3.0.0
 */
@RestController
@RequestMapping("/api/rest")
@CrossOrigin(origins = { "http://localhost:4300" })
public class MasterLookupWebService {

	private static final Logger LOG = LoggerFactory.getLogger( MasterLookupWebService.class);


	@Autowired
	private  MasterLookupService masterLookupService;

	@Autowired
	private IDMSBaseService idmsBaseService;

	
	@PostMapping("/createMasterLookup")
	public ResponseEntity<MasterLookupDTO> insertMasterLookup(@RequestBody MasterLookupDTO masterLookupDTO){
		try{
				if(masterLookupDTO!=null) {				
					StaffMember loginUser = idmsBaseService.currentUser();
					FormatConverterUtils.setInitialDefaultValues(masterLookupDTO, loginUser);
				
					MasterLookupDTO datamasterLookupDTO = masterLookupService.persistMasterLookup(masterLookupDTO);
					return new ResponseEntity<> (datamasterLookupDTO, HttpStatus.OK);
			}
		}catch (Exception e) {
			LOG.error("Error while inserting MasterLookup {}",e);
		}
		
		HttpHeaders headers= new HttpHeaders();
		return new ResponseEntity<>(headers, HttpStatus.NOT_IMPLEMENTED);
	}

	@GetMapping("/getAllMasterLookup")
	public ResponseEntity<List<MasterLookupDTO>> getAllMasterLookup() {
		List<MasterLookupDTO> masterLookupDTOResp;
		try {
			masterLookupDTOResp = masterLookupService.retrieveAllMasterLookup();
			return new ResponseEntity<> (masterLookupDTOResp, HttpStatus.OK);

		} catch (IdmsBaseException e) {
			LOG.error("Error while retrieving all  MasterLookup {}",e);
		}
		HttpHeaders headers= new HttpHeaders();
		return new ResponseEntity<>(headers, HttpStatus.NOT_IMPLEMENTED);
	}

	@GetMapping("/getMasterLookupById")
	public ResponseEntity<MasterLookupDTO> getMasterLookupById(@RequestParam("id") Long lookupId) {
	MasterLookupDTO masterLookupDTO;
		try {
			masterLookupDTO =  masterLookupService.retrieveMasterLookupById(lookupId);
			return new ResponseEntity<> (masterLookupDTO, HttpStatus.OK);
		} catch (IdmsBaseException e) {
			LOG.error("Error while retrieving By MasterLookup ID {}",e);
		}
		HttpHeaders headers= new HttpHeaders();
		return new ResponseEntity<>(headers , HttpStatus.NOT_IMPLEMENTED);
	}


	
	@PutMapping("/updateMasterLookup")
	public ResponseEntity<MasterLookupDTO> updateMasterLookup(@RequestBody MasterLookupDTO masterLookupDTO){
		try{
			  if(masterLookupDTO!=null) {				
				StaffMember loginUser = idmsBaseService.currentUser();
				FormatConverterUtils.setInitialDefaultValues(masterLookupDTO, loginUser);
				MasterLookupDTO datamasterLookupDTO = masterLookupService.updateMasterLookup(masterLookupDTO);
				return new ResponseEntity<> (datamasterLookupDTO, HttpStatus.OK);
			}
		}catch (Exception e) {
			LOG.error("Error while updating MasterLookup {}",e);
		}
		
		HttpHeaders headers= new HttpHeaders();
		return new ResponseEntity<>(headers, HttpStatus.NOT_IMPLEMENTED);
	}


	@DeleteMapping("/removeMasterLookupById")
	public ResponseEntity<Void> deleteMasterLookupById(@Valid @RequestParam("id") Long lookupId){
	HttpHeaders headers= new HttpHeaders();
		try {
			boolean flag = masterLookupService.deleteMasterLookupById(lookupId);
			if(flag)
				return new ResponseEntity<> (headers, HttpStatus.OK);
			else
				return new ResponseEntity<>(headers, HttpStatus.NOT_IMPLEMENTED);
		}catch (Exception e) {
			LOG.error("Error while deleting By MasterLookup ID {}",e);
		}
		
		return new ResponseEntity<>(headers, HttpStatus.NOT_IMPLEMENTED);
	
	}

}










