/*
 * Created on 2021-05-06 ( Date ISO 2021-05-06 - Time 17:00:24 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.idms.web.rest.admin;


import javax.validation.Valid;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.web.PagedResourcesAssembler;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.CrossOrigin;
import java.util.List;
import org.springframework.web.bind.annotation.RequestParam;
import com.cpa.idms.backend.dao.admin.entities.StaffMember;
import com.cpa.idms.backend.dao.exception.entities.IdmsBaseException;
import com.cpa.idms.service.admin.IDMSBaseService;
import com.cpa.idms.service.admin.ProjectUserService;
import com.cpa.idms.service.admin.dto.ProjectUserDTO;
import com.cpa.idms.util.FormatConverterUtils;



/**
 * Rest controller which produce Hal+json content (including hateoas metadata).
 * @author Rajol version 3.0.0
 */
@RestController
@RequestMapping("/api/rest")
@CrossOrigin(origins = { "http://localhost:4300" })
public class ProjectUserWebService {

	private static final Logger LOG = LoggerFactory.getLogger(ProjectUserWebService.class);


	@Autowired
	private  ProjectUserService projectUserService;

	@Autowired
	private IDMSBaseService idmsBaseService;

	
	@PostMapping("/createProjectUser")
	public ResponseEntity<ProjectUserDTO> insertProjectUser(@RequestBody ProjectUserDTO projectUserDTO){
		try{
				if(projectUserDTO!=null) {				
					StaffMember loginUser = idmsBaseService.currentUser();
					FormatConverterUtils.setInitialDefaultValues(projectUserDTO, loginUser);
				
					ProjectUserDTO dataprojectUserDTO = projectUserService.insertProjectUser(projectUserDTO);
					return new ResponseEntity<> (dataprojectUserDTO, HttpStatus.OK);
			}
		}catch (Exception e) {
			LOG.error("Error while inserting ProjectUser {}",e);
		}
		
		HttpHeaders headers= new HttpHeaders();
		return new ResponseEntity<>(headers, HttpStatus.NOT_IMPLEMENTED);
	}
	@GetMapping("/getAllProjectUser")
	public ResponseEntity<List<ProjectUserDTO>> getAllProjectUser() {
		List<ProjectUserDTO> projectUserDTOResp;
		try {
			projectUserDTOResp = projectUserService.retrieveAllProjectUser();
			return new ResponseEntity<> (projectUserDTOResp, HttpStatus.OK);

		} catch (IdmsBaseException e) {
			LOG.error("Error while retrieving all  ProjectUser {}",e);
		}
		HttpHeaders headers= new HttpHeaders();
		return new ResponseEntity<>(headers, HttpStatus.NOT_IMPLEMENTED);
	}

		@GetMapping("/getProjectUserById")
	public ResponseEntity<ProjectUserDTO> getProjectUserById(@RequestParam("id") Long projectUserId) {
	ProjectUserDTO projectUserDTO;
		try {
			projectUserDTO =  projectUserService.retrieveProjectUserById( projectUserId);
			return new ResponseEntity<> (projectUserDTO, HttpStatus.OK);
		} catch (IdmsBaseException e) {
			LOG.error("Error while retrieving By ProjectUser ID {}",e);
		}
		HttpHeaders headers= new HttpHeaders();
		return new ResponseEntity<>(headers , HttpStatus.NOT_IMPLEMENTED);
	}


	
	@PutMapping("/updateProjectUser")
	public ResponseEntity<ProjectUserDTO> updateProjectUser(@RequestBody ProjectUserDTO projectUserDTO){
		try{
			  if(projectUserDTO!=null) {				
				StaffMember loginUser = idmsBaseService.currentUser();
				FormatConverterUtils.setInitialDefaultValues(projectUserDTO, loginUser);
				ProjectUserDTO dataprojectUserDTO = projectUserService.updateProjectUser(projectUserDTO);
				return new ResponseEntity<> (dataprojectUserDTO, HttpStatus.OK);
			}
		}catch (Exception e) {
			LOG.error("Error while updating ProjectUser {}",e);
		}
		
		HttpHeaders headers= new HttpHeaders();
		return new ResponseEntity<>(headers, HttpStatus.NOT_IMPLEMENTED);
	}


	@DeleteMapping("/removeProjectUserById")
	public ResponseEntity<Void> deleteProjectUserById(@Valid @RequestParam("id") Long projectUserId){
	HttpHeaders headers= new HttpHeaders();
		try {
			Boolean flag = projectUserService.deleteById(projectUserId);
			if(flag)
				return new ResponseEntity<> (headers, HttpStatus.OK);
			else
				return new ResponseEntity<>(headers, HttpStatus.NOT_IMPLEMENTED);
		}catch (Exception e) {
			LOG.error("Error while deleting By ProjectUser ID {}",e);
		}
		
		return new ResponseEntity<>(headers, HttpStatus.NOT_IMPLEMENTED);
	
	}

}










