/*
 * Created on 2021-05-06 ( Date ISO 2021-05-06 - Time 17:00:25 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.idms.web.rest.admin;


import javax.validation.Valid;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.CrossOrigin;
import java.util.List;
import org.springframework.web.bind.annotation.RequestParam;
import com.cpa.idms.backend.dao.admin.entities.StaffMember;
import com.cpa.idms.backend.dao.exception.entities.IdmsBaseException;
import com.cpa.idms.service.admin.IDMSBaseService;
import com.cpa.idms.service.admin.WorkflowTemplateService;
import com.cpa.idms.service.admin.dto.WorkflowTemplateDTO;
import com.cpa.idms.util.FormatConverterUtils;



/**
 * Rest controller which produce Hal+json content (including hateoas metadata).
 * @author Rajol version 3.0.0
 */
@RestController
@RequestMapping("/api/rest")
@CrossOrigin(origins = { "http://localhost:4300" })
public class WorkflowTemplateWebService {

	private static final Logger LOG = LoggerFactory.getLogger(WorkflowTemplateWebService.class);


	@Autowired
	private  WorkflowTemplateService workflowTemplateService;

	@Autowired
	private IDMSBaseService idmsBaseService;

	
	@PostMapping("/createWorkflowTemplate")
	public ResponseEntity<WorkflowTemplateDTO> insertWorkflowTemplate(@RequestBody WorkflowTemplateDTO workflowTemplateDTO){
		try{
				if(workflowTemplateDTO!=null) {				
					StaffMember loginUser = idmsBaseService.currentUser();
					FormatConverterUtils.setInitialDefaultValues(workflowTemplateDTO, loginUser);
				
					WorkflowTemplateDTO dataworkflowTemplateDTO = workflowTemplateService.insertWorkflowTemplate(workflowTemplateDTO);
					return new ResponseEntity<> (dataworkflowTemplateDTO, HttpStatus.OK);
			}
		}catch (Exception e) {
			LOG.error("Error while inserting WorkflowTemplate {}",e);
		}
		
		HttpHeaders headers= new HttpHeaders();
		return new ResponseEntity<>(headers, HttpStatus.NOT_IMPLEMENTED);
	}

	@GetMapping("/getAllWorkflowTemplate")
	public ResponseEntity<List<WorkflowTemplateDTO>> getAllWorkflowTemplate() {
		List<WorkflowTemplateDTO> workflowTemplateDTOResp;
		try {
			workflowTemplateDTOResp = workflowTemplateService.retrieveAllWorkflowTemplate();
			return new ResponseEntity<> (workflowTemplateDTOResp, HttpStatus.OK);

		} catch (IdmsBaseException e) {
			LOG.error("Error while retrieving all  WorkflowTemplate {}",e);
		}
		HttpHeaders headers= new HttpHeaders();
		return new ResponseEntity<>(headers, HttpStatus.NOT_IMPLEMENTED);
	}

		@GetMapping("/getWorkflowTemplateById")
	public ResponseEntity<WorkflowTemplateDTO> getWorkflowTemplateById(@RequestParam("id") Long workflowTemplateId) {
	WorkflowTemplateDTO workflowTemplateDTO;
		try {
			workflowTemplateDTO =  workflowTemplateService.retrieveWorkflowTemplateById( workflowTemplateId);
			return new ResponseEntity<> (workflowTemplateDTO, HttpStatus.OK);
		} catch (IdmsBaseException e) {
			LOG.error("Error while retrieving By WorkflowTemplate ID {}",e);
		}
		HttpHeaders headers= new HttpHeaders();
		return new ResponseEntity<>(headers , HttpStatus.NOT_IMPLEMENTED);
	}


	
	@PutMapping("/updateWorkflowTemplate")
	public ResponseEntity<WorkflowTemplateDTO> updateWorkflowTemplate(@RequestBody WorkflowTemplateDTO workflowTemplateDTO){
		try{
			  if(workflowTemplateDTO!=null) {				
				StaffMember loginUser = idmsBaseService.currentUser();
				FormatConverterUtils.setInitialDefaultValues(workflowTemplateDTO, loginUser);
				WorkflowTemplateDTO dataworkflowTemplateDTO = workflowTemplateService.updateWorkflowTemplate(workflowTemplateDTO);
				return new ResponseEntity<> (dataworkflowTemplateDTO, HttpStatus.OK);
			}
		}catch (Exception e) {
			LOG.error("Error while updating WorkflowTemplate {}",e);
		}
		
		HttpHeaders headers= new HttpHeaders();
		return new ResponseEntity<>(headers, HttpStatus.NOT_IMPLEMENTED);
	}


	@DeleteMapping("/removeWorkflowTemplateById")
	public ResponseEntity<Void> deleteWorkflowTemplateById(@Valid @RequestParam("id") Long workflowTemplateId){
	HttpHeaders headers= new HttpHeaders();
		try {
			Boolean flag = workflowTemplateService.deleteById(workflowTemplateId);
			if(flag)
				return new ResponseEntity<> (headers, HttpStatus.OK);
			else
				return new ResponseEntity<>(headers, HttpStatus.NOT_IMPLEMENTED);
		}catch (Exception e) {
			LOG.error("Error while deleting By WorkflowTemplate ID {}",e);
		}
		
		return new ResponseEntity<>(headers, HttpStatus.NOT_IMPLEMENTED);
	
	}

}










