import {Organization} from '../../Organization/Organization'

export class StaffMember {
  constructor(public staffId: number,
              public loginId: string,
              public loginKey: string,
              public firstName: string,
              public middleName: string,
              public lastName: string,
              public staffImage: any,
              public providerType: string,
              public designation: string,
              public providerFlag: string,
              public organizationId: number, 
              public activeFlag: boolean,
              public clinicLocationId: number,
              public mobileNo: string,
              public businessPhoneNo: string,
              public email: string,
              public npiNumber: string,
              public lastClient: string,
              public lastAction: string,
              public lastLoginDate: string, 
              public lastActionDate: string, 
              public createdDate: Date,
              public createdBy: string,
              public lastUpdatedDate: Date,
              public lastUpdatedBy: string,
              public licenseState: string,
              public licenseNumber: string,
              public licenseExpDate: string,
              public deaNumber: string,
              public deaExpDate: string,
              public malpracticeCoverage: string,
              public malpracticeExpiration: Date,
              public dob: Date,
              public gender: string,
              public ssn: string
  ){}
} 