/*
 * Created on 2019-05-02 ( Date ISO 2019-05-02 - Time 11:00:43 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.ehr.backend.dao.preventivecare;


import java.util.List;

import javax.transaction.Transactional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import com.cpa.ehr.backend.dao.preventivecare.constants.MasterPreventitiveConstant;
import com.cpa.ehr.backend.dao.preventivecare.entities.MasterPreventiveCare;

@Repository
@Transactional
public interface MasterPreventiveCareRepository  extends JpaRepository<MasterPreventiveCare, String> 
{
	
	@Query(value = MasterPreventitiveConstant.FIND_ALL, nativeQuery = true)
	List<MasterPreventiveCare> getAllMasterPreventiveByGender(@Param("gender") String gender);
	
	@Query(value = MasterPreventitiveConstant.FIND_ALL_MASTER, nativeQuery = true)
	List<MasterPreventiveCare> getAllMasterPreventive();
}