/*
 * Created on 2021-05-06 ( Date ISO 2021-05-06 - Time 17:00:23 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.idms.service.admin.dto;

import java.util.Date;



/**
 * Hateoas resource associated with DocumentsVersionWorkflow.
 * @author Rajol version 3.0.0
 */
public class DocumentsVersionWorkflowDTO  {

	   private Long documentsVersionWorkflowId;  
	   private String approvalStatus;  
	   private String createdBy;  
	   private Date createdDate;  
	   private String docVersionReviewComments;  
	   private Long estimateDay;  
	   private Date expiryDate;  
	   private String filed1;  
	   private String field2;  
	   private String field3;  
	   private String field4;  
	   private String modifiedBy;  
	   private Date modifiedDate;  
	   private Long categoryId;  
	   private Long projectDocumentsVersionId;  
	   private Long projectDocumentsId;  
	   private Long staffId;  
	   private Long staffRoleId;  
	   private Long approverOrder;  

	// Constructor
	public DocumentsVersionWorkflowDTO() {
		// Needed empty constructor for serialization
	}

	public Long getDocumentsVersionWorkflowId() {
		return this.documentsVersionWorkflowId;
	}
	public void setDocumentsVersionWorkflowId(Long documentsVersionWorkflowId) {
		this.documentsVersionWorkflowId = documentsVersionWorkflowId;
	}
	public String getApprovalStatus() {
		return this.approvalStatus;
	}
	public void setApprovalStatus(String approvalStatus) {
		this.approvalStatus = approvalStatus;
	}
	public String getCreatedBy() {
		return this.createdBy;
	}
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}
	public Date getCreatedDate() {
		return this.createdDate;
	}
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	public String getDocVersionReviewComments() {
		return this.docVersionReviewComments;
	}
	public void setDocVersionReviewComments(String docVersionReviewComments) {
		this.docVersionReviewComments = docVersionReviewComments;
	}
	public Long getEstimateDay() {
		return this.estimateDay;
	}
	public void setEstimateDay(Long estimateDay) {
		this.estimateDay = estimateDay;
	}
	public Date getExpiryDate() {
		return this.expiryDate;
	}
	public void setExpiryDate(Date expiryDate) {
		this.expiryDate = expiryDate;
	}
	public String getFiled1() {
		return this.filed1;
	}
	public void setFiled1(String filed1) {
		this.filed1 = filed1;
	}
	public String getField2() {
		return this.field2;
	}
	public void setField2(String field2) {
		this.field2 = field2;
	}
	public String getField3() {
		return this.field3;
	}
	public void setField3(String field3) {
		this.field3 = field3;
	}
	public String getField4() {
		return this.field4;
	}
	public void setField4(String field4) {
		this.field4 = field4;
	}
	public String getModifiedBy() {
		return this.modifiedBy;
	}
	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}
	public Date getModifiedDate() {
		return this.modifiedDate;
	}
	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}
	public Long getCategoryId() {
		return this.categoryId;
	}
	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}
	public Long getProjectDocumentsVersionId() {
		return this.projectDocumentsVersionId;
	}
	public void setProjectDocumentsVersionId(Long projectDocumentsVersionId) {
		this.projectDocumentsVersionId = projectDocumentsVersionId;
	}
	public Long getProjectDocumentsId() {
		return this.projectDocumentsId;
	}
	public void setProjectDocumentsId(Long projectDocumentsId) {
		this.projectDocumentsId = projectDocumentsId;
	}
	public Long getStaffId() {
		return this.staffId;
	}
	public void setStaffId(Long staffId) {
		this.staffId = staffId;
	}
	public Long getStaffRoleId() {
		return this.staffRoleId;
	}
	public void setStaffRoleId(Long staffRoleId) {
		this.staffRoleId = staffRoleId;
	}
	public Long getApproverOrder() {
		return this.approverOrder;
	}
	public void setApproverOrder(Long approverOrder) {
		this.approverOrder = approverOrder;
	}

    @Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
	sb.append("DocumentsVersionWorkflowDTO");
		sb.append("documentsVersionWorkflowId :");
		sb.append(documentsVersionWorkflowId); 
		sb.append("approvalStatus :");
		sb.append(approvalStatus); 
		sb.append("|"); 
		sb.append("createdBy :");
		sb.append(createdBy); 
		sb.append("|"); 
		sb.append("createdDate :");
		sb.append(createdDate); 
		sb.append("|"); 
		sb.append("docVersionReviewComments :");
		sb.append(docVersionReviewComments); 
		sb.append("|"); 
		sb.append("estimateDay :");
		sb.append(estimateDay); 
		sb.append("|"); 
		sb.append("expiryDate :");
		sb.append(expiryDate); 
		sb.append("|"); 
		sb.append("filed1 :");
		sb.append(filed1); 
		sb.append("|"); 
		sb.append("field2 :");
		sb.append(field2); 
		sb.append("|"); 
		sb.append("field3 :");
		sb.append(field3); 
		sb.append("|"); 
		sb.append("field4 :");
		sb.append(field4); 
		sb.append("|"); 
		sb.append("modifiedBy :");
		sb.append(modifiedBy); 
		sb.append("|"); 
		sb.append("modifiedDate :");
		sb.append(modifiedDate); 
		sb.append("|"); 
		sb.append("categoryId :");
		sb.append(categoryId); 
		sb.append("|"); 
		sb.append("projectDocumentsVersionId :");
		sb.append(projectDocumentsVersionId); 
		sb.append("|"); 
		sb.append("projectDocumentsId :");
		sb.append(projectDocumentsId); 
		sb.append("|"); 
		sb.append("staffId :");
		sb.append(staffId); 
		sb.append("|"); 
		sb.append("staffRoleId :");
		sb.append(staffRoleId); 
		sb.append("|"); 
		sb.append("approverOrder :");
		sb.append(approverOrder); 
        return sb.toString();
    }

}


