/*
 * Created on 2021-05-06 ( Date ISO 2021-05-06 - Time 17:00:24 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.idms.service.admin.dto;

import java.util.Date;



/**
 * Hateoas resource associated with ProjectDocuments.
 * @author Rajol version 3.0.0
 */
public class ProjectDocumentsDTO  {

	   private Long projectDocumentsId;  
	   private Long activeVersionNo;  
	   private String archiveReason;  
	   private String createdBy;  
	   private Date createdDate;  
	   private String docStatus;  
	   private String docVisibility;  
	   private String filed1;  
	   private String field2;  
	   private String field3;  
	   private String field4;  
	   private String fileName;  
	   private String modifiedBy;  
	   private Date modifiedDate;  
	   private Date pdfConvertDate;  
	   private String pdfConvertStatus;  
	   private String pdfObjectId;  
	   private String pdfPath;  
	   private String projectDocName;  
	   private String rawObjectId;  
	   private String rawFilePath;  
	   private Date webConvDate;  
	   private String webCovStatus;  
	   private String webObjectId;  
	   private String webPath;  
	   private Long categoryId;  

	// Constructor
	public ProjectDocumentsDTO() {
		// Needed empty constructor for serialization
	}

	public Long getProjectDocumentsId() {
		return this.projectDocumentsId;
	}
	public void setProjectDocumentsId(Long projectDocumentsId) {
		this.projectDocumentsId = projectDocumentsId;
	}
	public Long getActiveVersionNo() {
		return this.activeVersionNo;
	}
	public void setActiveVersionNo(Long activeVersionNo) {
		this.activeVersionNo = activeVersionNo;
	}
	public String getArchiveReason() {
		return this.archiveReason;
	}
	public void setArchiveReason(String archiveReason) {
		this.archiveReason = archiveReason;
	}
	public String getCreatedBy() {
		return this.createdBy;
	}
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}
	public Date getCreatedDate() {
		return this.createdDate;
	}
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	public String getDocStatus() {
		return this.docStatus;
	}
	public void setDocStatus(String docStatus) {
		this.docStatus = docStatus;
	}
	public String getDocVisibility() {
		return this.docVisibility;
	}
	public void setDocVisibility(String docVisibility) {
		this.docVisibility = docVisibility;
	}
	public String getFiled1() {
		return this.filed1;
	}
	public void setFiled1(String filed1) {
		this.filed1 = filed1;
	}
	public String getField2() {
		return this.field2;
	}
	public void setField2(String field2) {
		this.field2 = field2;
	}
	public String getField3() {
		return this.field3;
	}
	public void setField3(String field3) {
		this.field3 = field3;
	}
	public String getField4() {
		return this.field4;
	}
	public void setField4(String field4) {
		this.field4 = field4;
	}
	public String getFileName() {
		return this.fileName;
	}
	public void setFileName(String fileName) {
		this.fileName = fileName;
	}
	public String getModifiedBy() {
		return this.modifiedBy;
	}
	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}
	public Date getModifiedDate() {
		return this.modifiedDate;
	}
	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}
	public Date getPdfConvertDate() {
		return this.pdfConvertDate;
	}
	public void setPdfConvertDate(Date pdfConvertDate) {
		this.pdfConvertDate = pdfConvertDate;
	}
	public String getPdfConvertStatus() {
		return this.pdfConvertStatus;
	}
	public void setPdfConvertStatus(String pdfConvertStatus) {
		this.pdfConvertStatus = pdfConvertStatus;
	}
	public String getPdfObjectId() {
		return this.pdfObjectId;
	}
	public void setPdfObjectId(String pdfObjectId) {
		this.pdfObjectId = pdfObjectId;
	}
	public String getPdfPath() {
		return this.pdfPath;
	}
	public void setPdfPath(String pdfPath) {
		this.pdfPath = pdfPath;
	}
	public String getProjectDocName() {
		return this.projectDocName;
	}
	public void setProjectDocName(String projectDocName) {
		this.projectDocName = projectDocName;
	}
	public String getRawObjectId() {
		return this.rawObjectId;
	}
	public void setRawObjectId(String rawObjectId) {
		this.rawObjectId = rawObjectId;
	}
	public String getRawFilePath() {
		return this.rawFilePath;
	}
	public void setRawFilePath(String rawFilePath) {
		this.rawFilePath = rawFilePath;
	}
	public Date getWebConvDate() {
		return this.webConvDate;
	}
	public void setWebConvDate(Date webConvDate) {
		this.webConvDate = webConvDate;
	}
	public String getWebCovStatus() {
		return this.webCovStatus;
	}
	public void setWebCovStatus(String webCovStatus) {
		this.webCovStatus = webCovStatus;
	}
	public String getWebObjectId() {
		return this.webObjectId;
	}
	public void setWebObjectId(String webObjectId) {
		this.webObjectId = webObjectId;
	}
	public String getWebPath() {
		return this.webPath;
	}
	public void setWebPath(String webPath) {
		this.webPath = webPath;
	}
	public Long getCategoryId() {
		return this.categoryId;
	}
	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

    @Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
	sb.append("ProjectDocumentsDTO");
		sb.append("projectDocumentsId :");
		sb.append(projectDocumentsId); 
		sb.append("activeVersionNo :");
		sb.append(activeVersionNo); 
		sb.append("|"); 
		sb.append("archiveReason :");
		sb.append(archiveReason); 
		sb.append("|"); 
		sb.append("createdBy :");
		sb.append(createdBy); 
		sb.append("|"); 
		sb.append("createdDate :");
		sb.append(createdDate); 
		sb.append("|"); 
		sb.append("docStatus :");
		sb.append(docStatus); 
		sb.append("|"); 
		sb.append("docVisibility :");
		sb.append(docVisibility); 
		sb.append("|"); 
		sb.append("filed1 :");
		sb.append(filed1); 
		sb.append("|"); 
		sb.append("field2 :");
		sb.append(field2); 
		sb.append("|"); 
		sb.append("field3 :");
		sb.append(field3); 
		sb.append("|"); 
		sb.append("field4 :");
		sb.append(field4); 
		sb.append("|"); 
		sb.append("fileName :");
		sb.append(fileName); 
		sb.append("|"); 
		sb.append("modifiedBy :");
		sb.append(modifiedBy); 
		sb.append("|"); 
		sb.append("modifiedDate :");
		sb.append(modifiedDate); 
		sb.append("|"); 
		sb.append("pdfConvertDate :");
		sb.append(pdfConvertDate); 
		sb.append("|"); 
		sb.append("pdfConvertStatus :");
		sb.append(pdfConvertStatus); 
		sb.append("|"); 
		sb.append("pdfObjectId :");
		sb.append(pdfObjectId); 
		sb.append("|"); 
		sb.append("pdfPath :");
		sb.append(pdfPath); 
		sb.append("|"); 
		sb.append("projectDocName :");
		sb.append(projectDocName); 
		sb.append("|"); 
		sb.append("rawObjectId :");
		sb.append(rawObjectId); 
		sb.append("|"); 
		sb.append("rawFilePath :");
		sb.append(rawFilePath); 
		sb.append("|"); 
		sb.append("webConvDate :");
		sb.append(webConvDate); 
		sb.append("|"); 
		sb.append("webCovStatus :");
		sb.append(webCovStatus); 
		sb.append("|"); 
		sb.append("webObjectId :");
		sb.append(webObjectId); 
		sb.append("|"); 
		sb.append("webPath :");
		sb.append(webPath); 
		sb.append("|"); 
		sb.append("categoryId :");
		sb.append(categoryId); 
        return sb.toString();
    }

}


