/*
 * Created on 2021-05-06 ( Date ISO 2021-05-06 - Time 17:00:26 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package com.cpa.idms.service.admin.dto;

import java.util.Date;



/**
 * Hateoas resource associated with WorkflowTemplateDetails.
 * @author Rajol version 3.0.0
 */
public class WorkflowTemplateDetailsDTO  {

	   private Long workflowTemplateDetailsId;  
	   private Long approverOrder;  
	   private String createdBy;  
	   private Date createdDate;  
	   private String filed1;  
	   private String field2;  
	   private String field3;  
	   private String field4;  
	   private String modifiedBy;  
	   private Date modifiedDate;  
	   private Long staffId;  
	   private Long workflowTemplateId;  
	   private Long staffRoleId;  

	// Constructor
	public WorkflowTemplateDetailsDTO() {
		// Needed empty constructor for serialization
	}

	public Long getWorkflowTemplateDetailsId() {
		return this.workflowTemplateDetailsId;
	}
	public void setWorkflowTemplateDetailsId(Long workflowTemplateDetailsId) {
		this.workflowTemplateDetailsId = workflowTemplateDetailsId;
	}
	public Long getApproverOrder() {
		return this.approverOrder;
	}
	public void setApproverOrder(Long approverOrder) {
		this.approverOrder = approverOrder;
	}
	public String getCreatedBy() {
		return this.createdBy;
	}
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}
	public Date getCreatedDate() {
		return this.createdDate;
	}
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	public String getFiled1() {
		return this.filed1;
	}
	public void setFiled1(String filed1) {
		this.filed1 = filed1;
	}
	public String getField2() {
		return this.field2;
	}
	public void setField2(String field2) {
		this.field2 = field2;
	}
	public String getField3() {
		return this.field3;
	}
	public void setField3(String field3) {
		this.field3 = field3;
	}
	public String getField4() {
		return this.field4;
	}
	public void setField4(String field4) {
		this.field4 = field4;
	}
	public String getModifiedBy() {
		return this.modifiedBy;
	}
	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}
	public Date getModifiedDate() {
		return this.modifiedDate;
	}
	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}
	public Long getStaffId() {
		return this.staffId;
	}
	public void setStaffId(Long staffId) {
		this.staffId = staffId;
	}
	public Long getWorkflowTemplateId() {
		return this.workflowTemplateId;
	}
	public void setWorkflowTemplateId(Long workflowTemplateId) {
		this.workflowTemplateId = workflowTemplateId;
	}
	public Long getStaffRoleId() {
		return this.staffRoleId;
	}
	public void setStaffRoleId(Long staffRoleId) {
		this.staffRoleId = staffRoleId;
	}

    @Override
	public String toString() {
		StringBuilder sb = new StringBuilder(); 
	sb.append("WorkflowTemplateDetailsDTO");
		sb.append("workflowTemplateDetailsId :");
		sb.append(workflowTemplateDetailsId); 
		sb.append("approverOrder :");
		sb.append(approverOrder); 
		sb.append("|"); 
		sb.append("createdBy :");
		sb.append(createdBy); 
		sb.append("|"); 
		sb.append("createdDate :");
		sb.append(createdDate); 
		sb.append("|"); 
		sb.append("filed1 :");
		sb.append(filed1); 
		sb.append("|"); 
		sb.append("field2 :");
		sb.append(field2); 
		sb.append("|"); 
		sb.append("field3 :");
		sb.append(field3); 
		sb.append("|"); 
		sb.append("field4 :");
		sb.append(field4); 
		sb.append("|"); 
		sb.append("modifiedBy :");
		sb.append(modifiedBy); 
		sb.append("|"); 
		sb.append("modifiedDate :");
		sb.append(modifiedDate); 
		sb.append("|"); 
		sb.append("staffId :");
		sb.append(staffId); 
		sb.append("|"); 
		sb.append("workflowTemplateId :");
		sb.append(workflowTemplateId); 
		sb.append("|"); 
		sb.append("staffRoleId :");
		sb.append(staffRoleId); 
        return sb.toString();
    }

}


