export class StaffDetails {
    constructor(
       
		public staffId:number,
		public organizationId: number,
		public loginId : string,
		public loginKey : string,
		public firstName : string,
		public middleName : string,
		public lastName: string,
		public providerFlag:string,
		public designation: string,
		public lastLoginDt: Date,
		public lastActionDt: String,
		public lastAction: string,
		public lastClient: string,
		public mobileNo: string,
		public businessPhoneNo: string,
		public providerType: string,
		public email:string,
		public staffImage: any,
		public staffRoleId: number,
		public staffrole: string,
		public staffAddressId: number,
		public locationId: number,
		public locName: string,
		public addressDoorNo: string,
		public addressStreet: string,
		public addressCity: string ,
		public addressState: string,
		public addressZip: string ,
		public activeFlag: string,
		public createdDate: Date,
		public createdBy: string,
		public lastUpdatedDate: Date,
		public lastUpdatedBy: string,
		public npiNumber: string,
		public licenseState: string,
		public licenseNumber: string,
		public licenseExpDate: string,
		public deaNumber: string,
		public deaExpDate: string,
		public malpracticeCoverage: string,
		public malpracticeExpiration: Date,
		public dob: Date,
		public gender: string,
		public ssn: string
	 ) { 
    }
 } 